version: '3.4'

################################################
# SERVICES
################################################
services:
    test-postgres:
        container_name: test_db
        image: postgres:15
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        volumes:
            - "./var/lib/postgresql:/var/lib/postgresql/data:cached"

    test-adminer:
        container_name: test_adminer
        links:
            - test-postgres:db
        image: adminer
        restart: always
        ports:
            - 8080:8080

    mailcatcher:
        restart: always
        image: dockage/mailcatcher:0.7.1
        ports:
            - "1080:1080"
            - "1025:1025"